SET IDENTITY_INSERT [dbo].[Flights] ON
INSERT INTO [dbo].[Flights] ([flightNo], [airline], [departureDate], [departureTime], [pilotCode], [crewCode], [origin], [destination], [availableClasses], [availableSeats], [totalSeats], [layover], [allowedPassengerTypes], [allowedBaggageTypes]) VALUES (1003, N'Delta airlines', N'1995-09-25', N'16:45:00', 4235, 7894, N'Trivandrum', N'California', N'business economy premium first-class', 200, 200, N'berlin', N'Adults', N'check-in carry-on')
INSERT INTO [dbo].[Flights] ([flightNo], [airline], [departureDate], [departureTime], [pilotCode], [crewCode], [origin], [destination], [availableClasses], [availableSeats], [totalSeats], [layover], [allowedPassengerTypes], [allowedBaggageTypes]) VALUES (1004, N'African airlines', N'2024-09-25', N'16:45:00', 8945, 8975, N'Montreal', N'California', N'business economy premium first-class', 200, 200, N'berlin', N'Adults', N'check-in carry-on')
INSERT INTO [dbo].[Flights] ([flightNo], [airline], [departureDate], [departureTime], [pilotCode], [crewCode], [origin], [destination], [availableClasses], [availableSeats], [totalSeats], [layover], [allowedPassengerTypes], [allowedBaggageTypes]) VALUES (1005, N'SriLankan airlines', N'2024-08-20', N'17:35:00', 6587, 1564, N'Montreal', N'New Delhi', N'business economy premium first-class', 200, 200, N'berlin', N'Adults Students', N'check-in carry-on')
INSERT INTO [dbo].[Flights] ([flightNo], [airline], [departureDate], [departureTime], [pilotCode], [crewCode], [origin], [destination], [availableClasses], [availableSeats], [totalSeats], [layover], [allowedPassengerTypes], [allowedBaggageTypes]) VALUES (1006, N'Air Canada', N'2024-07-04', N'18:55:00', 352, 542, N'Montreal', N'Paris', N'business economy premium first-class', 200, 200, N'berlin', N'Adults Students', N'check-in carry-on')
INSERT INTO [dbo].[Flights] ([flightNo], [airline], [departureDate], [departureTime], [pilotCode], [crewCode], [origin], [destination], [availableClasses], [availableSeats], [totalSeats], [layover], [allowedPassengerTypes], [allowedBaggageTypes]) VALUES (1007, N'KLM', N'2024-06-13', N'19:00:00', 897, 4875, N'Montreal', N'Stockholm', N'business economy', 145, 145, N'oman', N'Adults Students', N'check-in carry-on')
INSERT INTO [dbo].[Flights] ([flightNo], [airline], [departureDate], [departureTime], [pilotCode], [crewCode], [origin], [destination], [availableClasses], [availableSeats], [totalSeats], [layover], [allowedPassengerTypes], [allowedBaggageTypes]) VALUES (1008, N'Pan airlines', N'2024-05-08', N'20:10:00', 4235, 8952, N'Montreal', N'Trivandrum', N'business economy', 145, 145, N'oman', N'Adults Students Youths', N'check-in carry-on')
INSERT INTO [dbo].[Flights] ([flightNo], [airline], [departureDate], [departureTime], [pilotCode], [crewCode], [origin], [destination], [availableClasses], [availableSeats], [totalSeats], [layover], [allowedPassengerTypes], [allowedBaggageTypes]) VALUES (1009, N'Indigo', N'2024-04-06', N'01:20:00', 5612, 7842, N'Interlaken', N'California', N'business economy', 145, 145, N'oman', N'Adults Students Youths', N'check-in carry-on')
INSERT INTO [dbo].[Flights] ([flightNo], [airline], [departureDate], [departureTime], [pilotCode], [crewCode], [origin], [destination], [availableClasses], [availableSeats], [totalSeats], [layover], [allowedPassengerTypes], [allowedBaggageTypes]) VALUES (1010, N'Vistara', N'2024-03-17', N'02:40:00', 2134, 2354, N'Interlaken', N'New Delhi', N'economy first-class', 180, 180, N'oman', N'Adults Infants', N'check-in carry-on')
INSERT INTO [dbo].[Flights] ([flightNo], [airline], [departureDate], [departureTime], [pilotCode], [crewCode], [origin], [destination], [availableClasses], [availableSeats], [totalSeats], [layover], [allowedPassengerTypes], [allowedBaggageTypes]) VALUES (1011, N'Singapore', N'2025-02-10', N'07:50:00', 7845, 4875, N'Interlaken', N'Paris', N'economy first-class', 180, 180, N'Warsaw', N'Adults Infants', N'check-in carry-on')
INSERT INTO [dbo].[Flights] ([flightNo], [airline], [departureDate], [departureTime], [pilotCode], [crewCode], [origin], [destination], [availableClasses], [availableSeats], [totalSeats], [layover], [allowedPassengerTypes], [allowedBaggageTypes]) VALUES (1012, N'Malaysian', N'2025-01-02', N'13:05:00', 6325, 110, N'Interlaken', N'Stockholm', N'economy first-class', 180, 180, N'Warsaw', N'Adults Students Youths Children', N'check-in carry-on')
INSERT INTO [dbo].[Flights] ([flightNo], [airline], [departureDate], [departureTime], [pilotCode], [crewCode], [origin], [destination], [availableClasses], [availableSeats], [totalSeats], [layover], [allowedPassengerTypes], [allowedBaggageTypes]) VALUES (1013, N'British Airways', N'2024-12-01', N'21:20:00', 1002, 2254, N'Interlaken', N'Trivandrum', N'business economy', 180, 180, N'Warsaw', N'Adults Students Youths Children', N'check-in carry-on')
INSERT INTO [dbo].[Flights] ([flightNo], [airline], [departureDate], [departureTime], [pilotCode], [crewCode], [origin], [destination], [availableClasses], [availableSeats], [totalSeats], [layover], [allowedPassengerTypes], [allowedBaggageTypes]) VALUES (1014, N'Indian Airlines', N'2024-11-28', N'00:40:00', 999, 7548, N'Interlaken', N'Montreal', N'business economy', 145, 145, N'Warsaw', N'Adults Students Youths Children Toddler', N'check-in carry-on')
SET IDENTITY_INSERT [dbo].[Flights] OFF
